package hello.web;

import hello.entity.Greeting;
import hello.UserRepository;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller
public class GreetingController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/greeting")
    public String greetingForm(Model model) {
        model.addAttribute("greeting", new Greeting());
        return "greeting";
    }

    @PostMapping("/greeting")
    public String greetingSubmit(@ModelAttribute Greeting greeting) {

        Greeting g = new Greeting();

        g.setName(greeting.getName());
        g.setAge(greeting.getAge());
        g.setGender(greeting.getGender());
        g.setEmail(greeting.getEmail());
        g.setCity(greeting.getCity());
        userRepository.save(g);

        return "result";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Greeting> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

}
