package hello.web;

import hello.entity.Greeting;
import hello.UserRepository;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import org.springframework.beans.factory.annotation.Autowired;

import javax.validation.Valid;

@Controller
public class GreetingController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/greeting")
    public String greetingForm(Model model) {
        model.addAttribute("greeting", new Greeting());
        return "greeting";
    }

    @PostMapping("/greeting")
    public String greetingSubmit(@ModelAttribute Greeting greeting) {

        Greeting g = new Greeting();

        g.setName(greeting.getName());
        g.setAge(greeting.getAge());
        g.setGender(greeting.getGender());
        g.setEmail(greeting.getEmail());
        g.setCity(greeting.getCity());
        userRepository.save(g);

        return "result";

    }

    @GetMapping("/all")
    public String getMessage(Model model) {

        Iterable<Greeting> users = userRepository.findAll();

        model.addAttribute("users", users);
        return "all";
    }

}
